connections:
  - bidirectional: no
    hosts: [xhc, client]
  - bidirectional: yes
    hosts: [xhc, imc]
    {% include "test_config_common.yaml" indent content %}  # indentation when "indent content" keyword passed will be applied to every line of the included file

# outcome, when you'll pass test_config_example.yaml to the test:
#connections:
#  - bidirectional: no
#    hosts: [xhc, client]
#  - bidirectional: yes
#    hosts: [xhc, imc]
#    interval: 1.0
#    count: 3
#    direction: both
