ip_ver: 4
count: 10
src_port:
dst_port:
pcap_file: 0020-0x1a-01-MAC_IPV4_TCP.pcap
cp_host_name: imc
secrets:
  - name: first
    value: gAAAAABnVxEZMaIzgdPZBKsyYu0RMbfpBeDqWxbs_hJeTti3RsnQS8ROp-9ZgumRNEUDWDCsVtKZTSf9ZHxHVgIuOKnpvYvUql74hYGm03G7gL_7qjkxKMo=
  - name: second
    value: gAAAAABnVxEZMaIzgdPZBKsyYu0RMbfpBeDqWxbs_hJeTti3RsnQS8ROp-9ZgumRNEUDWDCsVtKZTSf9ZHxHVgIuOKnpvYvUql74hYGm03G7gL_7qjkxKMo=
connections:
  - bidirectional: no
    hosts: [xhc, client]
