---
metadata:                           # mandatory
  version: '2.4'
hosts:                              # each of the element of the topology_configs file is optional, but once provided we validate whether mandatory params are provided
- name: sut                         # mandatory
  instantiate: true                 # mandatory - determines whether Host object should be instantiated when using fixture
  role: sut                         # mandatory
  connections:                      # optional
  - ip_address: {{ ip_address }}
    connection_type: RPyCConnection
  - ip_address: {{ ip_address }}
    connection_type: SSHConnection
    connection_options:
      username: {{ 'root' if 'posix' in system.lower() else 'berta' }}
      password: {{ secret_password }}  # <------ Here you have provided name of the secret, not the value. The value will be retrieved from the secrets manager and injected into the connection options.
  - ip_address: 127.0.0.1
    connection_type: LocalConnection
- name: sut-2                       # mandatory
  instantiate: true                 # mandatory - determines whether Host object should be instantiated when using fixture
  role: sut                         # mandatory
  connections:                      # optional
  - ip_address: {{ ip_address }}
    connection_type: SSHConnection
    connection_options:
      username: {{ 'root' if 'posix' in system.lower() else 'berta' }}
      password: {{ plain_password }}
- name: sut-3                     # mandatory
  instantiate: false                # mandatory - determines whether Host object should be instantiated when using fixture
  role: sut                         # mandatory
  connections:                      # optional
  - mac_address: {{ mac_address }}
    connection_type: RPyCConnection
    osd_details:
      base_url: http://example.com/osd
      username: root
      password: {{ secret_password }}  # Secret password that needs to be decrypted (AMBER_ENCRYPTION_KEY needs to be set to do this)
switches:
- name: Dell ZF 1223456
  mng_ip_address: 10.1.2.4
  mng_user: foo
  mng_password: {{ secret_password }}  # Secret password that needs to be decrypted (AMBER_ENCRYPTION_KEY needs to be set to do this)
  instantiate: false
  switch_type: DellOS9_Force10
  device_type: Dell
  connection_type: SSHSwitchConnection
  power_mng:
    power_mng_type: Ipmi
    host: host
    username: root
    password: {{ secret_password }}
    connection:
      ip_address: 10.1.0.3
      connection_type: RPyCConnection
- name: Mellanox ZF XYZ
  mng_ip_address: 10.1.2.3
  mng_user: foo
  mng_password: pass
  instantiate: false
  switch_type: DellOS9_Force10
  device_type: Dell
  connection_type: SSHSwitchConnection
  power_mng:
    power_mng_type: Ipmi
    host: host
    username: root
    password: {{ plain_password }}
    connection:
      ip_address: 10.1.0.4
      connection_type: RPyCConnection