---
metadata:                           # mandatory
  version: '2.4'
hosts:                              # each of the element of the topology_configs file is optional, but once provided we validate whether mandatory params are provided
- name: sut                         # mandatory
  instantiate: true                  # mandatory - determines whether Host object should be instantiated when using fixture
  role: sut                         # mandatory
  connections:                      # optional
  - ip_address: {{ ip_address }}
    connection_type: RPyCConnection
  - ip_address: {{ ip_address }}
    connection_type: SSHConnection
    connection_options:
      username: {{ 'root' if 'posix' in system.lower() else 'berta' }}
      password: {{ secrets_password }}  # <------ Here you have provided name of the secret, not the value.
  - ip_address: 127.0.0.1               # The value will be retrieved from the secrets manager and injected into the connection options.
    connection_type: LocalConnection